let found: boolean = true;
let grade: number = 88.6;
let firstName: string ="aymen";
let lastName: string ='amri';
console.log(found);
console.log(grade);
console.log(firstName);
console.log(lastName);
console.log("hi "+firstName+" "+lastName);
console.log(`Hi ${firstName} ${lastName}`);
